pipeline:
  name: javaapp_bluegreen_pipeline
  identifier: javaapp_bluegreen_pipeline
  projectIdentifier: fisdemo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy-javaapp
        identifier: deployjavaapp
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: fisdemoapp2
          environment:
            environmentRef: fisdemodevdep
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradep
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
