apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-ui
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: javaapp-ui
  template:
    metadata:
      labels:
        app: javaapp-ui
    spec:
      containers:
      - image: <+artifact.image>
        name: javaapp-ui
        ports:
        - containerPort: 80
