apiVersion: v1
kind: Service
metadata:
  name: javaapp-service
spec:
  selector:
    app: java-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: javaapplication-ui
